apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-heal-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: self-heal-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: self-heal-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: self-heal-role
subjects:
  - kind: ServiceAccount
    name: self-heal-sa
    