apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits: 
              cpu: "500m"
              memory: "512Mi"