apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replica-patch.yaml  # ✅ no target selector

namePrefix: dev-
labels:
  - pairs:
      environment: dev