apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment

namePrefix: dev-
labels:
  - pairs:
      environment: dev
