apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
data:
  POSTGRES_USER: cG9zdGdyZXM=      # base64("postgres")
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64("password")
